{% set name = "suxarray" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66280811b09cde81e54e92dd4eafca15e5dc9d8890c37092c29a1e998363638a

build:
  entry_points:
    - suxarray=suxarray.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1


requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<3.11
    - uxarray >=2023.4.1
    - netcdf4
    - shapely >=2.0
    - click >=7.0


test:
  imports:
    - suxarray
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - suxarray --help

about:
  home: https://github.com/cadwrdeltamodeling/suxarray
  summary: SCHISM grid extension of uxarray
  description: |
    suxarray is an extension of uxarray for SCHISM grids and data.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://cadwrdeltamodeling.github.io/suxarray/
  dev_url: https://github.com/cadwrdeltamodeling/suxarray

extra:
  recipe-maintainers:
    - kjnam
