{% set name = "suxarray" %}
{% set version = "2025.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CADWRDeltaModeling/suxarray/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07fcce642020c3451d47da6a9bc9ecbf02476c6e83a0e7ad3facf53890b7417f

build:
  entry_points:
    - suxarray=suxarray.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0


requirements:
  host:
    - python >=3.8,<=3.12
    - pip
  run:
    - python >=3.8,<=3.12
    - uxarray ==2025.6.0
    - shapely >=2.0
    - click >=7.0
  run_constrained:
    - vtk

test:
  imports:
    - suxarray
  requires:
    - pip
  commands:
    - pip check
    - suxarray --help

about:
  home: https://github.com/cadwrdeltamodeling/suxarray
  summary: SCHISM grid extension of uxarray
  description: |
    suxarray is an extension of uxarray for SCHISM grids and data.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://cadwrdeltamodeling.github.io/suxarray/
  dev_url: https://github.com/cadwrdeltamodeling/suxarray

extra:
  recipe-maintainers:
    - kjnam
